name: ci

on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0

      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.1.5
        with:
          go-version: '1.17.x'

      - name: build
        run: go build -o apko ./cmd/apko/main.go

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0

      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.1.5
        with:
          go-version: '1.17.x'

      - name: test
        run: go test ./...
