on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  cli:
    name: Release the CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ko-build:
    name: Release apko image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write  # undocumented OIDC support.
      packages: write
      contents: read

    env:
      KO_DOCKER_REPO: ghcr.io/mattmoor/apko
      KOFLAGS: --platform=all --bare
      COSIGN_EXPERIMENTAL: "true"

    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.17.x
    - uses: imjasonh/setup-ko@v0.4
      with:
        version: v0.10.0
    - uses: sigstore/cosign-installer@main
    - uses: actions/checkout@v2
    - name: Publish apko image
      run: |
        DIGEST=$(ko build ${KOFLAGS} --tags $(basename "${{ github.ref }}" ),latest ./cmd/apko)

        cosign sign ${DIGEST}
